### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by linogaliana** [pierre-lamarche/carpenteR#3]
Avec `usethis::use_travis`, tu as un *template* pour l'intégration continue directement utilisable pour faire un `check` d'un :package: `R`.

J'ai voulu le créer sur mon `fork` mais ça initie `travis` sur mon compte donc je pense que tu dois le faire toi-même.

**Comment by linogaliana** [comment]
Le rendu final est visible [là](https://github.com/linogaliana/carpenteR/tree/travis) mais je vais pas te faire de `PR` pour que s'assurer que les *build* CI soient faits sur ton compte

**Comment by pierre-lamarche** [comment]
Normalement activé désormais, merci beaucoup pour le conseil !!
